import React from "react";

const INNER_SPEED = 0.035;
const MIDDLE_SPEED = -0.025;
const OUTER_SPEED = 0.018;

const orbitData = [
  // ---- INNER RING (4 items, ringTotal = 4, idx 0-3) ----
  {
    id: 1,
    name: "React",
    icon: <i className="ri-reactjs-line text-cyan-400" />,
    color: "cyan",
    ring: "inner",
    speed: INNER_SPEED,
    ringIdx: 0,
    ringTotal: 4,
  },
  {
    id: 2,
    name: "Flutter",
    icon: <i className="ri-flutter-line text-blue-400" />,
    color: "blue",
    ring: "inner",
    speed: INNER_SPEED,
    ringIdx: 1,
    ringTotal: 4,
  },
  {
    id: 3,
    name: "FastAPI",
    icon: <i className="ri-server-line text-pink-400" />,
    color: "rose",
    ring: "inner",
    speed: INNER_SPEED,
    ringIdx: 2,
    ringTotal: 4,
  },
  {
    id: 4,
    name: "API",
    icon: <i class="ri-webhook-line text-pink-400"></i>,
    color: "rose",
    ring: "inner",
    speed: INNER_SPEED,
    ringIdx: 3,
    ringTotal: 4,
  },

  // ---- MIDDLE RING (5 items, ringTotal = 5, idx 0-4) ----
  {
    id: 5,
    name: "Dart",
    icon: <i className="ri-code-s-slash-line text-cyan-300" />,
    color: "sky",
    ring: "middle",
    speed: MIDDLE_SPEED,
    ringIdx: 0,
    ringTotal: 5,
  },
  {
    id: 6,
    name: "JavaScript",
    icon: <i className="ri-javascript-line text-yellow-300" />,
    color: "amber",
    ring: "middle",
    speed: MIDDLE_SPEED,
    ringIdx: 1,
    ringTotal: 5,
  },
  {
    id: 7,
    name: "Java",
    icon: <i className="ri-cup-line text-orange-300" />,
    color: "orange",
    ring: "middle",
    speed: MIDDLE_SPEED,
    ringIdx: 2,
    ringTotal: 5,
  },
  {
    id: 8,
    name: "Kotlin",
    icon: <i className="ri-android-line text-purple-300" />,
    color: "purple",
    ring: "middle",
    speed: MIDDLE_SPEED,
    ringIdx: 3,
    ringTotal: 5,
  },
  {
    id: 9,
    name: "Python",
    icon: <i className="ri-terminal-box-line text-green-300" />,
    color: "lime",
    ring: "middle",
    speed: MIDDLE_SPEED,
    ringIdx: 4,
    ringTotal: 5,
  },

  // ---- OUTER RING (6 items, ringTotal = 6, idx 0-5) ----
  {
    id: 10,
    name: "AI / ML",
    icon: <i className="ri-brain-line text-yellow-400" />,
    color: "yellow",
    ring: "outer",
    speed: OUTER_SPEED,
    ringIdx: 0,
    ringTotal: 6,
  },
  {
    id: 11,
    name: "Firebase",
    icon: <i className="ri-fire-line text-yellow-400" />,
    color: "red",
    ring: "outer",
    speed: OUTER_SPEED,
    ringIdx: 1,
    ringTotal: 6,
  },
  {
    id: 12,
    name: "Supabase",
    icon: <i className="ri-database-2-line text-green-400" />,
    color: "teal",
    ring: "outer",
    speed: OUTER_SPEED,
    ringIdx: 2,
    ringTotal: 6,
  },
  {
    id: 13,
    name: "Tailwind CSS",
    icon: <i className="ri-css3-line text-cyan-400" />,
    color: "cyan",
    ring: "outer",
    speed: OUTER_SPEED,
    ringIdx: 3,
    ringTotal: 6,
  },
  {
    id: 14,
    name: "GitHub",
    icon: <i className="ri-github-line text-purple-300" />,
    color: "indigo",
    ring: "outer",
    speed: OUTER_SPEED,
    ringIdx: 4,
    ringTotal: 6,
  },
  {
    id: 15,
    name: "SQL",
    icon: <i className="ri-server-line text-blue-300" />,
    color: "blue",
    ring: "outer",
    speed: OUTER_SPEED,
    ringIdx: 5,
    ringTotal: 6,
  },
];

export default orbitData;